version: '3'
services:
  java-app:
    image: demoapp
    environment:
      - DB_USER=${DB_USER} 
      - DB_PWD=${DB_PWD} 
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
    ports:
    - 8080:8080
    container_name: my-java-app 
  mysql: 
    image: mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    - mysql-data:/var/lib/mysql
    container_name: mysql
    #command: --default-authentication-plugin=mysql_native_password
  phpmyadmin: 
    image: phpmyadmin
    environment:
      - PMA_HOST=${PMA_HOST}
    ports:
      - 8083:80
    container_name: myadmin    
volumes:
  mysql-data:
    driver: local
